var class_data = {
    "0": {
        "code": "AA",
        "name": "Amber Aegis",
        "race": "Harrower",
        "icon": "Beetle",
        "version": "crimson-scales",
        "id_start": "003",
        "id_stop": "032",
        "max_cards": 11.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "1": {
        "code": "BK",
        "name": "Brightspark",
        "race": "Human",
        "icon": "Flask",
        "version": "crimson-scales",
        "id_start": "029",
        "id_stop": "058",
        "max_cards": 11.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "2": {
        "code": "BM",
        "name": "Bombard",
        "race": "Quatryl",
        "icon": "Target",
        "version": "crimson-scales",
        "id_start": "001",
        "id_stop": "028",
        "max_cards": 9.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "3": {
        "code": "CG",
        "name": "Chainguard",
        "race": "Inox",
        "icon": "Chainguard",
        "version": "crimson-scales",
        "id_start": "059",
        "id_stop": "087",
        "max_cards": 10.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "4": {
        "code": "CT",
        "name": "Chieftain",
        "race": "Orchid",
        "icon": "Tusks",
        "version": "crimson-scales",
        "id_start": "088",
        "id_stop": "116",
        "max_cards": 10.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "5": {
        "code": "FK",
        "name": "Fire Knight",
        "race": "Valrath",
        "icon": "Ladder Axe",
        "version": "crimson-scales",
        "id_start": "117",
        "id_stop": "145",
        "max_cards": 10.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "6": {
        "code": "HO",
        "name": "Hollowpact",
        "race": "Savvas",
        "icon": "Vortex",
        "version": "crimson-scales",
        "id_start": "184",
        "id_stop": "212",
        "max_cards": 10.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "7": {
        "code": "HP",
        "name": "Hierophant",
        "race": "Human",
        "icon": "Leaf",
        "version": "crimson-scales",
        "id_start": "146",
        "id_stop": "183",
        "max_cards": 11.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "8": {
        "code": "LU",
        "name": "Luminary",
        "race": "Lurker",
        "icon": "Cresent Sun",
        "version": "crimson-scales",
        "id_start": "213",
        "id_stop": "242",
        "max_cards": 11.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "9": {
        "code": "MF",
        "name": "Mirefoot",
        "race": "Quatryl",
        "icon": "Sprig",
        "version": "crimson-scales",
        "id_start": "243",
        "id_stop": "271",
        "max_cards": 10.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "10": {
        "code": "RM",
        "name": "Ruinmaw",
        "race": "Vermling",
        "icon": "Bleeding Claw",
        "version": "crimson-scales",
        "id_start": "003",
        "id_stop": "032",
        "max_cards": 11.0,
        "base_hp": 8.0,
        "hp_growth": 1.5,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "11": {
        "code": "SP",
        "name": "Spirit Caller",
        "race": "Vermling",
        "icon": "Skull",
        "version": "crimson-scales",
        "id_start": "272",
        "id_stop": "300",
        "max_cards": 10.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "12": {
        "code": "ST",
        "name": "Starslinger",
        "race": "Aesther",
        "icon": "Galaxy",
        "version": "crimson-scales",
        "id_start": "301",
        "id_stop": "329",
        "max_cards": 10.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "13": {
        "code": "QA",
        "name": "Artificer",
        "race": "Quatryl",
        "icon": "Tools",
        "version": "crimson-scales",
        "id_start": "003",
        "id_stop": "030",
        "max_cards": 9.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "14": {
        "code": "DR",
        "name": "Diviner",
        "race": "Aesther",
        "icon": null,
        "version": "forgotten-circles",
        "id_start": "574",
        "id_stop": "601",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "15": {
        "code": "BB",
        "name": "Blink Blade",
        "race": "Quatryl",
        "icon": null,
        "version": "frosthaven",
        "id_start": "032",
        "id_stop": "060",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A complex character who uses a system of tokens to move different speeds and use crowd control and deal damage on some rounds while be less effective on others."
    },
    "16": {
        "code": "BN",
        "name": "Banner Spear",
        "race": "Human",
        "icon": null,
        "version": "frosthaven",
        "id_start": "061",
        "id_stop": "089",
        "max_cards": 10.0,
        "base_hp": 8.0,
        "hp_growth": 2.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A tanky damage dealer who works with allies in special formation area attacks that require allies in order to work."
    },
    "17": {
        "code": "BO",
        "name": "Boneshaper",
        "race": "Aesther",
        "icon": null,
        "version": "frosthaven",
        "id_start": "120",
        "id_stop": "150",
        "max_cards": 12.0,
        "base_hp": 5.0,
        "hp_growth": 1.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A summon-based character with non-loss summons that cost HP."
    },
    "18": {
        "code": "DF",
        "name": "Drifter",
        "race": "Inox",
        "icon": null,
        "version": "frosthaven",
        "id_start": "001",
        "id_stop": "031",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A jack of all trades who manipulates persistent multi-use tracks on their loss cards to empower various abilities."
    },
    "19": {
        "code": "DW",
        "name": "Deathwalker",
        "race": "Valrath",
        "icon": null,
        "version": "frosthaven",
        "id_start": "090",
        "id_stop": "119",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A damage dealer who uses placed shadow tokens resulting from enemy deaths to do strong damage and movement effects."
    },
    "20": {
        "code": "GE",
        "name": "Geminate",
        "race": "Harrower",
        "icon": null,
        "version": "frosthaven",
        "id_start": "151",
        "id_stop": "184",
        "max_cards": 14.0,
        "base_hp": 7.0,
        "hp_growth": 1.5,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "An area attacker with two forms, each with their own separate hands; one melee-focused and one ranged-focus, who swap between them by playing specific effects"
    },
    "21": {
        "code": "CR",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "474",
        "id_stop": "504",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "22": {
        "code": "DT",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "445",
        "id_stop": "473",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "23": {
        "code": "FF",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "360",
        "id_stop": "386",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "24": {
        "code": "HV",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "387",
        "id_stop": "416",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "25": {
        "code": "IF",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "185",
        "id_stop": "214",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "26": {
        "code": "ME",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "417",
        "id_stop": "444",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "27": {
        "code": "PC",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "301",
        "id_stop": "329",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "28": {
        "code": "PY",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "215",
        "id_stop": "243",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "29": {
        "code": "SD",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "330",
        "id_stop": "359",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "30": {
        "code": "SH",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "244",
        "id_stop": "272",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "31": {
        "code": "TA",
        "name": null,
        "race": null,
        "icon": null,
        "version": "frosthaven",
        "id_start": "273",
        "id_stop": "300",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "32": {
        "code": "BE",
        "name": "Berserker",
        "race": "Inox",
        "icon": "Lightning Bolt",
        "version": "gloomhaven",
        "id_start": "319",
        "id_stop": "347",
        "max_cards": 10.0,
        "base_hp": 8.0,
        "hp_growth": 2.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "33": {
        "code": "BR",
        "name": "Brute",
        "race": "Inox",
        "icon": null,
        "version": "gloomhaven",
        "id_start": "001",
        "id_stop": "029",
        "max_cards": 10.0,
        "base_hp": 8.0,
        "hp_growth": 2.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A very simple tanky class who has a minor specialization in movement."
    },
    "34": {
        "code": "BS",
        "name": null,
        "race": null,
        "icon": null,
        "version": "gloomhaven",
        "id_start": "624",
        "id_stop": "653",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "35": {
        "code": "BT",
        "name": "The Beast Tyrant",
        "race": null,
        "icon": "Two-Mini",
        "version": "gloomhaven",
        "id_start": "476",
        "id_stop": "505",
        "max_cards": 10.0,
        "base_hp": 5.0,
        "hp_growth": 1.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "36": {
        "code": "CH",
        "name": "Cragheart",
        "race": "Savvas",
        "icon": null,
        "version": "gloomhaven",
        "id_start": "116",
        "id_stop": "145",
        "max_cards": 11.0,
        "base_hp": 8.0,
        "hp_growth": 2.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A jack of all trades with a focus on area damage and obstacle use."
    },
    "37": {
        "code": "DS",
        "name": "Doomstalker",
        "race": "Orchid",
        "icon": "Angry Face",
        "version": "gloomhaven",
        "id_start": "376",
        "id_stop": "406",
        "max_cards": 12.0,
        "base_hp": 6.5,
        "hp_growth": 1.5,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "38": {
        "code": "EL",
        "name": "Elementalist",
        "race": "Savvas",
        "icon": "Triforce",
        "version": "gloomhaven",
        "id_start": "447",
        "id_stop": "475",
        "max_cards": 10.0,
        "base_hp": 5.0,
        "hp_growth": 1.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "39": {
        "code": "MT",
        "name": "Mindthief",
        "race": "Vermling",
        "icon": null,
        "version": "gloomhaven",
        "id_start": "146",
        "id_stop": "174",
        "max_cards": 10.0,
        "base_hp": 5.0,
        "hp_growth": 1.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A fairly complex melee attacker with a unique augment system who can use crowd control abilities to disable enemies."
    },
    "40": {
        "code": "NS",
        "name": "Nightshroud",
        "race": "Aesther",
        "icon": "Eclipse",
        "version": "gloomhaven",
        "id_start": "261",
        "id_stop": "288",
        "max_cards": 9.0,
        "base_hp": 6.5,
        "hp_growth": 1.5,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "41": {
        "code": "PH",
        "name": "Plagueherald",
        "race": "Harrower",
        "icon": "Cthulhu",
        "version": "gloomhaven",
        "id_start": "289",
        "id_stop": "318",
        "max_cards": 11.0,
        "base_hp": 5.0,
        "hp_growth": 1.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "42": {
        "code": "QM",
        "name": "Quartermaster",
        "race": "Valrath",
        "icon": "Three Spears",
        "version": "gloomhaven",
        "id_start": "205",
        "id_stop": "232",
        "max_cards": 9.0,
        "base_hp": 8.0,
        "hp_growth": 2.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "43": {
        "code": "SC",
        "name": "Scoundrel",
        "race": "Human",
        "icon": null,
        "version": "gloomhaven",
        "id_start": "088",
        "id_stop": "89",
        "max_cards": 9.0,
        "base_hp": 6.5,
        "hp_growth": 1.5,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A high damage melee attacker who specializes in moving in and out of melee while gaining benefits from adjacent allies."
    },
    "44": {
        "code": "SK",
        "name": "Sunkeeper",
        "race": "Valrath",
        "icon": "Sun",
        "version": "gloomhaven",
        "id_start": "175",
        "id_stop": "204",
        "max_cards": 11.0,
        "base_hp": 8.0,
        "hp_growth": 2.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "45": {
        "code": "SB",
        "name": "Sawbones",
        "race": "Human",
        "icon": "Saw",
        "version": "gloomhaven",
        "id_start": "407",
        "id_stop": "446",
        "max_cards": 10.0,
        "base_hp": 6.5,
        "hp_growth": 1.5,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "46": {
        "code": "SS",
        "name": "Soothsinger",
        "race": "Quatryl",
        "icon": "Music Note",
        "version": "gloomhaven",
        "id_start": "348",
        "id_stop": "375",
        "max_cards": 9.0,
        "base_hp": 5.0,
        "hp_growth": 1.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "47": {
        "code": "SU",
        "name": "Summoner",
        "race": "Aesther",
        "icon": "Circles",
        "version": "gloomhaven",
        "id_start": "233",
        "id_stop": "260",
        "max_cards": 9.0,
        "base_hp": 6.5,
        "hp_growth": 1.5,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "48": {
        "code": "SW",
        "name": "Spellweaver",
        "race": "Orchid",
        "icon": null,
        "version": "gloomhaven",
        "id_start": "061",
        "id_stop": "087",
        "max_cards": 8.0,
        "base_hp": 5.0,
        "hp_growth": 1.0,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A somewhat complex ranged area attacker with a unique stamina system that allows her to play losses more freely."
    },
    "49": {
        "code": "TI",
        "name": "Tinkerer",
        "race": "Quatryl",
        "icon": null,
        "version": "gloomhaven",
        "id_start": "030",
        "id_stop": "060",
        "max_cards": 12.0,
        "base_hp": 6.5,
        "hp_growth": 1.5,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A healing-based support who can play losses to make up for his shortcomings in terms of damage."
    },
    "50": {
        "code": "DE",
        "name": "Demolitionist",
        "race": "Quatryl",
        "icon": null,
        "version": "jaws-of-the-lion",
        "id_start": "073",
        "id_stop": "109",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A melee attacker who destroys obstacles for various attacks."
    },
    "51": {
        "code": "HA",
        "name": "Hatchet",
        "race": "Inox",
        "icon": null,
        "version": "jaws-of-the-lion",
        "id_start": "001",
        "id_stop": "038",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A ranged attacker who uses their favorite hatchet to do massive damage, but must retrieve it thereafter."
    },
    "52": {
        "code": "RG",
        "name": "Red Guard",
        "race": "Valrath",
        "icon": null,
        "version": "jaws-of-the-lion",
        "id_start": "215",
        "id_stop": "252",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "A light- and fire-base tank class who can use a specific card to let their shield cards output damage."
    },
    "53": {
        "code": "VW",
        "name": "Voidwarden",
        "race": "Human",
        "icon": null,
        "version": "jaws-of-the-lion",
        "id_start": "142",
        "id_stop": "180",
        "max_cards": null,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": "An element-based control mage who can force enemies to act or grant their allies actions or other benefits."
    },
    "54": {
        "code": "IN",
        "name": "Incarnate",
        "race": "Inox",
        "icon": "Three-Eyes",
        "version": "trail-of-ashes",
        "id_start": "488",
        "id_stop": "517",
        "max_cards": 11.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "55": {
        "code": "RH",
        "name": "Rimehearth",
        "race": "Savvas",
        "icon": "Ice Meteor",
        "version": "trail-of-ashes",
        "id_start": "519",
        "id_stop": "547",
        "max_cards": 10.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "56": {
        "code": "SR",
        "name": "Shardrender",
        "race": "Orchid",
        "icon": "Gemstone",
        "version": "trail-of-ashes",
        "id_start": "549",
        "id_stop": "578",
        "max_cards": 11.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "57": {
        "code": "TP",
        "name": "Tempest",
        "race": "Orchid",
        "icon": "Lightning Ball",
        "version": "trail-of-ashes",
        "id_start": "580",
        "id_stop": "608",
        "max_cards": 10.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    },
    "58": {
        "code": "TR",
        "name": "Thornreaper",
        "race": "Orchid",
        "icon": "Spiked Ring",
        "version": "trail-of-ashes",
        "id_start": "610",
        "id_stop": "639",
        "max_cards": 11.0,
        "base_hp": null,
        "hp_growth": null,
        "Unnamed: 10": null,
        "Unnamed: 11": null,
        "Unnamed: 12": null,
        "desc": null
    }
};